## A Seminar Series Website Template
# This is a Jekyll + Bootstrap starter template for seminar series websites, designed to showcase speakers, archive past talks, and provide a clean, responsive layout.
# It includes features like speaker photos, event details, and optional junior speaker sections.
# It is built by the Khan Lab at MBZUAI and can be easily customized for any academic seminar series.

version: "1.0.1"

title: "Informatics for Life & Medicine (ILM) Seminars"
tagline: "By the School of Digital Public Health, MBZUAI"
description: "<b>ILM</b> is a flagship seminar series fostering collaboration in computational biology, AI, and systems medicine. Monthly talks with international and regional speakers, plus trainee spotlights."

info_text: "&dagger;The acronym <strong>ILM</strong> is inspired by the Arabic word 'ilm’ (علم), <a href='https://en.wikipedia.org/wiki/Ilm_(Arabic)' target='_blank'> knowledge, learning, or science(s)</a>."

organization: "MBZUAI, Abu Dhabi"
department: "Department of Computational Biology"

logo: "/assets/img/logo.png"

# Social media links
image: "/assets/img/share.jpg"

author: "Aziz Khan"
email: "aziz.khan@mbzuai.ac.ae"

url: "https://khanlab.bio/ilm-seminars/"
baseurl: ""
subscribe_url: "https://example.com/subscribe" # e.g., a newsletter signup link

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
exclude: [Gemfile, Gemfile.lock, node_modules, vendor]

# Bootstrap / Bootswatch config
bootswatch:
  # Set to a Bootswatch theme name (lowercase) or leave empty to use default Bootstrap
  # Examples: flatly, darkly, cosmo, cyborg, litera, lumen, lux, materia, minty,
  # morph, pulse, quartz, sandstone, simplex, sketchy, slate, solar, spacelab,
  # superhero, united, vapor, yeti, zephyr, cerulean, journal
  theme: ""
  version: "5.3.7" # do not change this unless you know what you're doing
  enabled_switcher: true # or false to hide the selector entirely

ilm:
  { timezone: "+04:00", default_duration_min: 60, venue: "MBZUAI, Abu Dhabi" }
nav:
  - { title: Home, url: / }
  - { title: About, url: /about/ }
  - { title: All Seminars, url: /events/ }
  - { title: Organizers, url: /organizers/ }
