services:
  swt-khanlab:
    build: .
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    entrypoint: ["./start.sh"]

volumes:
  bundle:
